title = "Terry.Wang"
baseURL = "http://terry.wang"
languageCode = "en-us"
theme = "terry"

############################## Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

#################### default parameters ################################
[params]
# logo = "images/logo.png"
# logo_height = "35px"
favicon = "images/favicon.png"
    